repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-json
      - id: check-xml
      - id: check-toml
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-symlinks
      - id: check-merge-conflict
      - id: fix-byte-order-marker

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0  # Specify the desired version of Gitleaks
    hooks:
    - id: gitleaks

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.2
    hooks:
    -   id: ruff
        args:
        - --fix
    -   id: ruff-format

-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest
        stages: [commit]
        types: [python]
        entry: pytest -v
        language: system
        pass_filenames: false
        always_run: true

-   repo: local
    hooks:
    - id: pycache-clean-up
      name: pycache-clean-up
      entry: bash -c 'find . -type d -name __pycache__ -exec rm -r {} \+'
      language: system
      types: [python]
      pass_filenames: false
